# data augmentation
dataset:
  common:
    NAME: BioVista # Name of the dataset see openpoint/datasets/ for list of available datasets. Should match with the class name in the dataset module.
    data_root: /workspace/datasets/test_3D_point_cloud_pipeline/100_high_and_100_low_HNV-forest-proxy-samples_30_m_circles_dataset.csv
  train:
    split: train
    num_points: 8192
  val:
    split: val
  test:
    split: test

num_points: 8192
feature_keys: pos
num_classes: 2
batch_size: 2
val_batch_size: 2

dataloader:
  num_workers: 4

datatransforms:
  train: [PointsToTensor, PointCloudScaling, PointCloudXYZAlign, PointCloudRotation, PointCloudJitter]
  val: [PointsToTensor, PointCloudXYZAlign]
  vote: []
  kwargs:
    color_drop: 0.2
    gravity_dim: 2
    scale: [0.9, 1.1]
    angle: [0, 0, 1]
    jitter_sigma: 0.005
    jitter_clip: 0.02

# ---------------------------------------------------------------------------- #
# Training cfgs
# ---------------------------------------------------------------------------- #
val_fn: validate
ignore_index: null 
epochs: 20

cls_weighed_loss: True

criterion_args:
  NAME: CrossEntropy
  label_smoothing: 0.2

optimizer:
 NAME: 'adamw'  # performs 1 point better than adam
 weight_decay: 1.0e-4

# lr_scheduler:
sched: cosine
warmup_epochs: 0

min_lr: 1.0e-5 #
lr: 0.01 # LR linear rule.

grad_norm_clip: 10
use_voting: False
# ---------------------------------------------------------------------------- #
# io and misc
# ---------------------------------------------------------------------------- #
save_freq: 1 # save epoch every xxx epochs, -1 only save last and best. 
val_freq: 1

wandb:
  use_wandb: False
  project: biovista-pointvector